"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Errors = void 0;
exports.Errors = {
    ADMIN_POST_USERS: "Only admins can add new users",
    ADMIN_POST_FEEDBACK: "Admin cannot give feedbacks",
    ADMIN_EDIT_FEEDBACK: "Only users can edit their feedback",
    ADMIN_DELETE_ADMIN: "Admin cannot delete another admin",
    ADMIN_NOT_FOUND: "Admin not found",
    NOT_ADMIN: "User is not authorized as admin",
    ADMIN_EDIT_USER: "Admin cannot edit user details",
    USER_NAME_REQUIRED: "User name is required",
    USER_ID_REQUIRED: "User id is required",
    USER_PASSWORD_INCORRECT: "Incorrect password",
    USER_POST_OWN_FEEDBACK: "User cannot post feedbacks about themselves",
    USER_EDIT_OTHERS_FEEDBACK: "User cannot update other user's feedbacks",
    DUPLICATE_EMAIL: "User with this email already exists",
    USER_NOT_FOUND: "User not found",
    USER_UPDATE_FIELD_REQUIRED: "Updates field cannot be empty",
    TECHNOLOGY_NAME_REQUIRED: "Technology name is required",
    TECHNOLOGY_DETAILS_REQUIRED: "Technology details is required",
    TECHNOLOGY_NOT_FOUND: "Technology not found",
    DUPLICATE_TECHNOLOGY: "Technology with this name already exists",
    FEEDBACK_NAME_REQUIRED: "Feedback name is required",
    FEEDBACK_ID_REQUIRED: "Feedback id is required",
    FEEDBACK_REQUIRED: "Feedback is required",
    FEEDBACK_STATUS_REQUIRED: "Feedback status is required",
    FEEDBACK_STATUS_INCORRECT: "Feedback status can be 'approved' or 'rejected' only",
    FEEDBACK_EMPTY: "Feedback cannot be empty",
    FEEDBACK_NOT_FOUND: "Feedback not found",
    FEEDBACK_USER_COUNT_EXIST: "Count with this name already exists",
    NAME_NOT_FOUND: "Name not found",
    DATE_FORMAT_INCORRECT: "Only accepted date format is 'YYYY-MM-DD'",
    INTERNAL_ERROR: "Internal error",
    BAD_REQUEST: "Bad request",
    INVALID_DATE: "Invalid date",
    AUTHORIZATION_FAILED: "Authorization failed",
    DATABASE_CONNECTION_FAILED: "Database connection failed, retry"
};
